apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mr6syk317-go 
  janus-idp.io/tekton: mr6syk317-go
  backstage.io/kubernetes-id: mr6syk317-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mr6syk317-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml